
switch:
  - platform: "mqtt"
    name: Tradfri Control Outlet
    state_topic: "zigbee2mqtt/tradfri_control_outlet"
    #    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_control_outlet/set"

  - platform: "mqtt"
    name: Tradfri Control Outlet 2
    state_topic: "zigbee2mqtt/tradfri_control_outlet_2"
    #    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_control_outlet_2/set"

homeassistant:
  customize:
    switch.tradfri_control_outlet:
      friendly_name: Fan
      icon: mdi:fan

    light.tradfri_control_outlet_light:
      friendly_name: Bathroom Light
      icon: mdi:lamp

