type: vertical-stack
cards:
  - type: glance
    title: Balcony
    entities:
      - sensor.balcony_temperature
      - sensor.balcony_humidity
      - sensor.balcony_pressure
      - sensor.br_condition

  - type: glance
    title: Hallway
    entities:
      - sensor.hallway_temperature
      - sensor.hallway_humidity
      - sensor.hallway_pressure
