type: vertical-stack
cards:
  - type: glance
    title: Outdoors
    entities:
      - sensor.outside_temperature
      - sensor.outside_humidity
      - sensor.outside_pressure
      - sensor.br_condition
  - type: glance
    title: Indoors
    entities:
      - sensor.inside_temperature
      - sensor.inside_humidity
      - sensor.inside_pressure
      - sensor.illuminance
