input_boolean:
  home_in_use:
    name: Home in use
    initial: 'off'

binary_sensor:
  - platform: "template"
    sensors:
      home:
        friendly_name: Home
        value_template: "{{ is_state('input_boolean.home_in_use', 'on') }}"
        device_class: occupancy

automation:
  - id: home_is_in_use
    alias: Home is in use
    trigger:
      - platform: state
        entity_id: person.roman_peters
        to: 'home'
      - platform: state
        entity_id: binary_sensor.kitchen_in_use
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_in_use
        to: 'on'
      - platform: state
        entity_id: binary_sensor.room_in_use
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_in_use

  - id: home_is_not_in_use
    alias: Home is not in use
    trigger:
      - platform: state
        entity_id: person.roman_peters
        to: 'not_home'
      - platform: state
        entity_id: binary_sensor.contact_sensor
        to: 'off'
    condition:
      - condition: state
        entity_id: person.roman_peters
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_in_use

  - id: enter_home_music
    alias: Enter Home Music
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ state_attr('media_player.sonos', 'media_content_type') == 'music' }}"
      - condition: state
        entity_id: 'binary_sensor.night'
        state: 'off'
    action:
      - wait_template: "{{ is_state('binary_sensor.contact_sensor', 'on') }}"
        timeout: '00:00:30'
        continue_on_timeout: 'true'
      - wait_template: "{{ is_state('binary_sensor.contact_sensor', 'off') }}"
        timeout: '00:00:30'
        continue_on_timeout: 'true'
      - service: media_player.media_play
        entity_id: media_player.sonos
      

