input_boolean:
  home_in_use:
    name: Home in use

binary_sensor:
  - platform: "template"
    sensors:
      home:
        friendly_name: Home
        value_template: "{{ is_state('input_boolean.home_in_use', 'on') }}"
        device_class: occupancy

automation:
  - id: home_is_in_use
    alias: Home is in use
    trigger:
      - platform: state
        entity_id: person.roman_peters
        to: 'home'
      - platform: state
        entity_id: binary_sensor.kitchen_in_use
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_in_use
        to: 'on'
      - platform: state
        entity_id: binary_sensor.room_in_use
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_in_use

  - id: home_is_not_in_use
    alias: Home is not in use
    trigger:
      - platform: state
        entity_id: person.roman_peters
        to: 'not_home'
      - platform: state
        entity_id: binary_sensor.contact_sensor
        to: 'off'
    condition:
      - condition: state
        entity_id: person.roman_peters
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_in_use

  # Leave Home
  - id: leave_home
    alias: Leave Home
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.leave_home
      - service: script.broadcast
        data:
          message: 'Bye 👋🏼'


  - id: enter_home
    alias: Enter Home
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'on'
    action:
      - service: script.broadcast
        data:
          message: 'Welcome home!'

  - id: enter_home_music
    alias: Enter Home Music
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ state_attr('media_player.sonos', 'media_content_type') == 'music' }}"
      - condition: state
        entity_id: 'binary_sensor.night'
        state: 'off'
    action:
      - service: media_player.media_play
        entity_id: media_player.sonos
