input_boolean:
  kitchen_in_use:
    name: Kitchen in use

binary_sensor:
  - platform: "template"
    sensors:
      kitchen_occupied:
        friendly_name: Kitchen
        value_template: "{{ is_state('input_boolean.kitchen_in_use', 'on') }}"
        device_class: occupancy

automation:
  - id: kitchen_turn_on
    alias: Kitchen turn on
    trigger:
      - platform: state
        entity_id: binary_sensor.miji_motion_sensor
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_in_use

  - id: kitchen_turn_off
    alias: Kitchen turn off
    trigger:
      - platform: state
        entity_id: binary_sensor.miji_motion_sensor
        to: 'off'
        for:
          minutes: 3
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_in_use


  # Turn on the light
  - id: kitchen_in_use
    alias: Kitchen in use
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupied
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.aqara_white_bulb
          brightness_pct: >
            {% if is_state("binary_sensor.dark", "on")  and  is_state("binary_sensor.night_mode", "on") -%}
              5
            {% elif is_state("binary_sensor.dark", "on") -%}
              60
            {%- else -%}
              0
            {%- endif %}

  # Turn off the light
  - id: kitchen_out_of_use
    alias: Kitchen out of use
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupied
        to: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.aqara_white_bulb
          transition: 60

homeassistant:
  customize:
    binary_sensor.kitchen_occupied:
      icon: mdi:run
