# On alarm

- alias: Wake up light
  trigger:
    - platform: time
      minutes: '/5'
      seconds: 00

  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int + 1800) | timestamp_custom("%H:%M") == states.input_select.alarm_time.state }}'
    - condition: state
      entity_id: input_boolean.smart_alarm
      state: 'on'

  action: 
    - service: script.wake_up
