language: python
python:
- 3.6.4
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config
before_install:
- openssl aes-256-cbc -K $encrypted_d9be15c6b9e8_key -iv $encrypted_d9be15c6b9e8_iv
  -in secrets.yaml.enc -out secrets.yaml -d
