language: python
python:
  - "3.6.4"
before_install:
  - mv secrets.yaml.example secrets.yaml
  - mv zones.yaml.example zones.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config