#- action:
#  - service: homeassistant.turn_on
#    entity_id: group.coloredlight
#  alias: At sunset
#  id: '1495372885472'
#  trigger:
#    platform: sun
#    event: sunset
#  condition:
#    - condition: state
#      entity_id: group.person_roman
#      state: 'home'

- action:
    service: script.boot
  alias: Boot
  id: '1495372885473'
  trigger:
    platform: homeassistant
    event: start

- action: 
    service: script.wake_up
  alias: Wake up light
  id: '1495372885474'
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int + 1800) | timestamp_custom("%H:%M") == states.input_select.alarm_time.state }}'
    - condition: state
      entity_id: input_boolean.smart_alarm
      state: 'on'

- alias: 'Start transition'
  trigger:
    platform: state
    entity_id: input_select.transition
  action:
    - service_template: "script.{{ states.input_select.transition.state }}"

- alias: 'Start scene'
  trigger:
    platform: state
    entity_id: input_select.scene
  action:
    service: scene.turn_on
    data_template:
      entity_id: "scene.{{ states.input_select.scene.state }}"

- alias: Television on
  trigger:
    platform: state
    entity_id: switch.g
    state: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.apple_tv
      data:
        visible: True


- alias: Television off
  trigger:
    platform: state
    entity_id: switch.g
    state: 'off'
  action:
    service: group.set_visibility
    entity_id: group.apple_tv
    data:
      visible: False

- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '1'
  action:
    service: script.power_off
- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '5'
  action:
    service: script.power_off
- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '15'
  action:
    service: script.power_off
- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '30'
  action:
    service: script.power_off
- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '60'
  action:
    service: script.power_off
- alias: 'Start power off'
  trigger:
    platform: state
    entity_id: input_select.power_off
    to: '120'
  action:
    service: script.power_off


- alias: Power_off script activated
  trigger:
    platform: state
    entity_id: script.power_off
    state: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.power_off
      data:
        visible: False
    - service: group.set_visibility
      entity_id: group.power_off_activated
      data:
        visible: True

- alias: Power_off script deactivated
  trigger:
    platform: state
    entity_id: script.power_off
    state: 'off'
  action:
    - service: group.set_visibility
      entity_id: group.power_off_activated
      data:
        visible: False
    - service: group.set_visibility
      entity_id: group.power_off
      data:
        visible: True
    - service: input_select.select_option
      data:
        entity_id: input_select.power_off
        option: 0

- alias: Dim at midnight
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: scene.turn_on
      data: 
        entity_id: scene.dim










