- platform: "template"
  sensors:
    outside_cooler_than_inside:
      friendly_name: "Outside cooler than inside"
      value_template: "{{ (states('sensor.br_temperature') | float) < (states('sensor.aqara_temperature') | float) }}"

    entone:
      friendly_name: "Entone is on"
      value_template: "{{ is_state('switch.entone', 'on') }}"
      delay_on: "00:01:20"
      
- platform: "mqtt"
  name: Window
  state_topic: "zigbee2mqtt/aqara_contact_sensor_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "window"
  json_attributes_topic: "zigbee2mqtt/aqara_contact_sensor_2"

- platform: "mqtt"
  name: Aqara motion sensor
  state_topic: "zigbee2mqtt/aqara_motion_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
  json_attributes_topic: "zigbee2mqtt/aqara_motion_sensor"
