- platform: "template"
  sensors:
    outside_cooler_than_inside:
      friendly_name: "Outside cooler than inside"
      value_template: "{{ (states('sensor.br_temperature') | float) < (states('sensor.aqara_temperature') | float) }}"

    entone:
      friendly_name: "Entone is on"
      value_template: "{{ is_state('switch.entone', 'on') }}"
      delay_on: "00:01:20"
