- platform: "template"
  sensors:
    home:
      friendly_name: "Home"
      icon_template: mdi:home
      value_template: "{{ states('input_boolean.home') == 'on' }}"
      device_class: presence

    dark:
      friendly_name: "It's dark"
      value_template: "{{ not is_state('sun.sun', 'above_horizon') and is_state('group.lights', 'off') }}"

    outside_cooler_than_inside:
      friendly_name: "Outside cooler than inside"
      value_template: "{{ (states('sensor.br_temperature') | float) < (states('sensor.inside_temperature') | float) }}"

    door_icon:
      friendly_name: "Door"
      icon_template: >
        {% if is_state('binary_sensor.door', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door
        {% endif %}
      value_template: "{{ is_state('binary_sensor.door', 'on') }}"

    television:
      friendly_name: "TV is on"
      value_template: "{{ is_state('switch.television', 'on') }}"
      delay_on: "00:00:10"

    entone:
      friendly_name: "Entone is on"
      value_template: "{{ is_state('switch.entone', 'on') }}"
      delay_on: "00:01:20"

- platform: "mqtt"
  name: Door
  state_topic: "zigbee2mqtt/door_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:door"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Motion sensor
  state_topic: "zigbee2mqtt/motion_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:run-fast"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Coffee button
  state_topic: "sonoff/binary_sensor/coffee_button/state"
  availability_topic: "sonoff/status"
  icon: "mdi:coffee"

- platform: "mqtt"
  name: Camera motion sensor
  icon: mdi:run-fast
  state_topic: xiaomi/dafang/motion
  device_class: motion
