#Home Assistant configuration
homeassistant:
  name: Dashboard
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize
  customize_domain: !include customize_domain.yaml

http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3

#device_sun_light_trigger:
#  light_group: group.lichten
#  light_profile: relax
#  device_group: group.person_roman

#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret

frontend:
  themes: !include themes.yaml

homekit:
  pincode: !secret homekit_pin

logger:
  default: warn

tts:
  platform: google

config:
updater:
discovery:
ios:
sun:
conversation:
logbook:

group: !include_dir_merge_named groups
automation: !include_dir_merge_named automations
scene: !include_dir_merge_named scenes
script: !include_dir_named scripts

zone: !include zones.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml
media_player: !include media_players.yaml
input_select: !include input_selects.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
device_tracker: !include device_trackers.yaml
shell_command: !include shell_commands.yaml













