homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret lonitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize.yaml

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:
  include_used_components: true

frontend:
config:
hassio:
history:
logbook:
ios:
tts:
  - platform: google

xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_aqara_key

light: !include lights.yaml
group: !include_dir_merge_named groups
switch: !include switches.yaml
sensor: !include sensors.yaml
panel_iframe: !include panel_iframes.yaml
