homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam

http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.10.10.10
#  trusted_networks:
#    - 10.10.10.10

#  ssl:
#    ssl_certificate: /ssl/fullchain.pem 
#    ssl_key: /ssl/privkey.pem

frontend:
#  javascript_version: es5
  themes: !include themes.yaml

mqtt:
#  discovery: true
#  broker: core-mosquitto
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

hassio:
system_health:
auth:
config:

light: !include lights.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
plant: !include plants.yaml
device_tracker: !include device_trackers.yaml
