homeassistant:
        #  name: Home
  #  latitude: !secret latitude
  #  longitude: !secret longitude
  #  elevation: 40
  #  unit_system: metric
  #  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize
  whitelist_external_dirs:
    - /config
  packages: !include_dir_named packages


http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies:
    - 172.1.1.1
    - 172.17.0.0/24
    - 10.10.10.20

#  trusted_networks:
#    - 10.10.10.10

#  ssl:
#    ssl_certificate: /ssl/fullchain.pem 
#    ssl_key: /ssl/privkey.pem

frontend:
#  javascript_version: es5
  themes: !include themes.yaml

mqtt:
#  discovery: true
  broker: 10.10.10.20
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

weather:
  - platform: buienradar
    name: Utrecht
    
transmission:
  host: transmission
  username: ""
  password: ""

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:
person:
system_health:
auth:
config:
history:
map:
python_script:
media_extractor:
conversation:
sun:
ios:
mobile_app:

shell_command:
  install_deps: 'apt update && apt install -y vlc'

tts:
  - platform: google_translate

recorder:
        #  db_url: !secret db_url

        #influxdb:
        #  host: 10.10.10.20

logbook: !include logbook.yaml
#automation: !include automations.yaml
automation yaml: !include_dir_merge_list automations
light: !include lights.yaml
group: !include_dir_merge_named groups
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
panel_iframe: !include panel_iframes.yaml
script: !include_dir_merge_named scripts
history_graph: !include history_graphs.yaml
input_select: !include input_selects.yaml
scene: !include_dir_merge_named scenes
climate: !include climates.yaml
input_text: !include input_texts.yaml
input_number: !include input_numbers.yaml
device_tracker: !include device_trackers.yaml
notify: !include notifies.yaml
media_player: !include media_players.yaml
zone: !include zones.yaml

