homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize

http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.10.10.10
#  trusted_networks:
#    - 10.10.10.10

#  ssl:
#    ssl_certificate: /ssl/fullchain.pem 
#    ssl_key: /ssl/privkey.pem

frontend:
#  javascript_version: es5
  themes: !include themes.yaml

mqtt:
#  discovery: true
  broker: 10.10.10.20
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

weather:
  - platform: buienradar
    name: Utrecht

mqtt_eventstream:
  subscribe_topic: satellite/events

system_health:
auth:
config:
history:
map:
python_script:
media_extractor:
conversation:
sun:
ios:


google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret


tts:
  - platform: google

recorder:
  db_url: !secret db_url

apple_tv:
  - host: 10.10.10.4
    login_id: !secret apple_tv_id

logbook: !include logbook.yaml
automation: !include_dir_merge_list automations
light: !include lights.yaml
group: !include_dir_merge_named groups
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
panel_iframe: !include panel_iframes.yaml
script: !include_dir_merge_named scripts
homekit: !include homekit.yaml
history_graph: !include history_graphs.yaml
alarm_control_panel: !include alarm_control_panels.yaml
plant: !include plants.yaml
input_select: !include input_selects.yaml
input_boolean: !include input_booleans.yaml
scene: !include scenes.yaml
climate: !include climates.yaml
timer: !include timers.yaml
input_text: !include input_texts.yaml
input_number: !include input_numbers.yaml
input_datetime: !include input_datetimes.yaml
device_tracker: !include device_trackers.yaml
notify: !include notifies.yaml
media_player: !include media_players.yaml
calendar: !include calendars.yaml
