homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:
  include_used_components: true

frontend:
config:
hassio:
history:
logbook:
python_script:
ios:
tts:
  - platform: google

recorder:
  db_url: !secret db_url

# xiaomi_aqara:
#   discovery_retry: 5
#   gateways:
#     - key: !secret xiaomi_aqara_key

feedreader:
  urls:
    - https://www.home-assistant.io/atom.xml

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

# fan: !include fans.yaml


automation: !include_dir_merge_list automations
light: !include lights.yaml
group: !include_dir_merge_named groups
switch: !include switches.yaml
sensor: !include sensors.yaml
panel_iframe: !include panel_iframes.yaml
script: !include_dir_merge_named scripts
#homekit: !include homekit.yaml
history_graph: !include history_graphs.yaml
alarm_control_panel: !include alarm_control_panels.yaml
plant: !include plants.yaml
input_select: !include input_selects.yaml

