#Home Assistant configuration
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 40
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize

http:
  api_password: !secret http_password

tts:
  platform: google

hassio:
config:
updater:
ios:
logbook:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

light: !include lights.yaml
group: !include_dir_merge_named groups
switch: !include switches.yaml

# homekit: !include homekit.yaml
# history_graph: !include history_graphs.yaml













