# HB hidden domains
apple_tv:
  homebridge_hidden: true
automation:
  homebridge_hidden: true
broadlink:
  homebridge_hidden: true
conversation:
  homebridge_hidden: true
device_tracker:
  homebridge_hidden: true
frontend:
  homebridge_hidden: true
google:
  homebridge_hidden: true
group:
  homebridge_hidden: true
homeassistant:
  homebridge_hidden: true
input_boolean:
  homebridge_hidden: true
input_select:
  homebridge_hidden: true
input_slider:
  homebridge_hidden: true
logbook:
  homebridge_hidden: true
media_player:
  homebridge_hidden: true
notify:
  homebridge_hidden: true
persistent_notification:
  homebridge_hidden: true
shell_command:
  homebridge_hidden: true
tts:
  homebridge_hidden: true