- platform: tile
  username: !secret tile_username
  password: !secret tile_password
  show_inactive: true

#- platform: bluetooth_tracker
#- platform: bluetooth_le_tracker

- platform: mqtt
  devices:
    macbook_pro: satellite/device_tracker/macbook_pro/state
    ipad: satellite/device_tracker/ipad/state
    iphone_8: satellite/device_tracker/iphone_8/state
    samsung_galaxy_s7: satellite/device_tracker/samsung_galaxy_s7/state

- platform: ping
  hosts:
    macbook_pro: 10.10.10.1
    samsung_galaxy_s7: 10.10.10.9
    acer_swift: 10.10.10.8
