- platform: bluetooth_tracker

  #- platform: bluetooth_le_tracker
  #  track_new_devices: false

  #- platform: tile
  #  username: !secret tile_username
  #  password: !secret tile_password
  #  show_inactive: true

  #- platform: ping
  #  hosts:
  #    macbook_pro: 10.10.10.1
