- platform: tile
  username: !secret tile_username
  password: !secret tile_password
  show_inactive: true

- platform: bluetooth_tracker

#- platform: bluetooth_le_tracker

- platform: ping
  hosts:
    macbook_pro: 10.10.10.1
    samsung_galaxy_s7: 10.10.10.9
    acer_swift: 10.10.10.8
