- platform: bluetooth_tracker

- platform: bluetooth_le_tracker
  track_new_devices: false

- platform: tile
  username: !secret tile_username
  password: !secret tile_password
  show_inactive: true

#- platform: icloud
#  username: !secret icloud_username
#  password: !secret icloud_password
#  account_name: icloud_roman

- platform: ping
  hosts:
    macbook_pro: 10.10.10.1
    samsung_galaxy_s7: 10.10.10.9
    acer_swift: 10.10.10.8
