- platform: limitlessled
  bridges:
    - host: '192.168.1.200'
      port: 8899
      version: 5
      groups:
      - number: 1
        type: rgbw
        name: Standing lamp
      - number: 2
        type: rgbw
        name: LED Strip N
      - number: 3
        type: rgbw
        name: LED strip S
      - number: 1
        type: white
        name: Ceiling lamp

- platform: blinkt