- platform: limitlessled
  bridges:
    - host: "192.168.1.1"
      port: 8899
      version: 5
      groups:
      - number: 1
        type: rgbw
        name: A  # Standing Lamp
      - number: 2
        type: rgbw
        name: B  # LED Strip N
      - number: 3
        type: rgbw
        name: C  # LED strip S
      - number: 1
        type: white
        name: D  # Ceiling Lamp

- platform: blinkt
