- platform: limitlessled
  bridges:
    - host: "10.10.10.201"
      port: 8899
      version: 5
      groups:
      - number: 1
        type: rgbw
        name: Ceiling Lamp
      - number: 2
        type: rgbw
        name: LED Strip N
      - number: 3
        type: rgbw
        name: LED strip S
      - number: 1
        type: white
        name: Standing Lamp

- platform: blinkt

- platform: mqtt_json
  name: Coffee LED
  brightness: true
  flash: true
  state_topic: "sonoff/light/coffee_led/state"
  command_topic: "sonoff/light/coffee_led/command"
  availability_topic: "sonoff/status"
  icon: "mdi:led"

- platform: template
  lights:
    tv_light:
      friendly_name: "TV Light"
      turn_on:
        service: switch.broadlink_send_packet_10_10_10_203
        data:
          packet:
          - "JgBYAAABJpYSExI4ETgRFBITEhQQFRE4EjcSOBAVETgSExI4ETgSExEVETgRFBITEhMRFBIUERQROBITEjgROBI3ETkROBI4EQAFGwABJ0sRAAxPAAEmTBAADQU"
      turn_off:
        service: switch.broadlink_send_packet_10_10_10_203
        data:
          packet:
          - "JgBYAAABJpYRFBE5EDkRFRAVEBQRFRA5EDkSORAVDzkRFRE4EDkSFBAVETkQFRAUETkQFg8WDxYQORAVEDkROREUEDkRORA5EAAFHQABJ0sRAAxQAAElTBEADQU"

- platform: mqtt
  name: "TV Backlight"
  command_topic: "homeassistant/light/tv_backlight/command"
  brightness_command_topic: "homeassistant/light/tv_backlight/brightness"
  rgb_command_topic: "homeassistant/light/tv_backlight/rgb"
  effect_command_topic: "homeassistant/light/tv_backlight/effect"
  effect_list:
    - strobe
    - flash
    - fade 
    - rgb fade

- platform: group
  name: LED Strips
  entities:
    - light.led_strip_n
    - light.led_strip_s

- platform: group
  name: Ambient Lights
  entities:
    - light.led_strip_n
    - light.led_strip_s
    - light.ceiling_lamp
    - light.tv_backlight
