#- platform: yeelight_bt
#  devices:
#    candela:
#      mac: 'f8:24:41:c1:6b:f4'

- platform: mqtt
  name: Aqara White Bulb
  state_topic: "zigbee2mqtt/aqara_white_bulb"
  brightness: true
  color_temp: true
  schema: "json"
  command_topic: "zigbee2mqtt/aqara_white_bulb/set"

- platform: mqtt
  name: Tradfri RGBW Bulb
  state_topic: "zigbee2mqtt/tradfri_rgbw_bulb"
  brightness: true
  color_temp: true
  xy: true
  schema: "json"
  command_topic: "zigbee2mqtt/tradfri_rgbw_bulb/set"

- platform: mqtt
  name: Candela
  state_topic: "satellite/light/candela/state"
  brightness_command_topic: "satellite/light/candela/brightness"
  command_topic: "satellite/light/candela/command"
#  availability_topic: "satellite/status"

#- platform: mqtt
#  name: Coffee LED
#  brightness: true
#  flash: true
#  state_topic: "sonoff/light/coffee_led/state"
#  command_topic: "sonoff/light/coffee_led/command"
#  availability_topic: "sonoff/status"

#- platform: mqtt
#  name: Heater LED
#  brightness: true
#  flash: true
#  state_topic: "sonoff2/light/heater_led/state"  #"sonoff_th10/light/heater_led/state"
#  command_topic: "sonoff2/light/heater_led/command"  #"sonoff_th10/light/heater_led/command"
#  availability_topic: "sonoff2/status"  #"sonoff_th10/status"


