- platform: vlc
  name: Intel NUC

- platform: plex

- platform: universal
  name: Television
  children:
    - media_player.apple_tv
  commands:
    turn_on: 
      service: switch.turn_on
      data: 
        entity_id: switch.television
    turn_off:
      service: switch.turn_off
      data: 
        entity_id: switch.television
    volume_up:
      service: script.turn_on
      data: 
        entity_id: script.sony_volume_higher
    volume_down:
      service: script.turn_on
      data: 
        entity_id: script.sony_volume_lower
    volume_mute:
      service: script.turn_on
      data: 
        entity_id: script.sony_mute
