#Home Assistant sensors
- platform: buienradar
  monitored_conditions:
    - condition
    - humidity
    - temperature
    - windspeed
    - precipitation
    - precipitation_forecast_total

- platform: minecraft
  name: Minecraft
  server: !secret minecraft_server

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  monitored_conditions:
    - temperature

- platform: template
  sensors:
    inside_temperature:
      unit_of_measurement: '°C'
      # Offset sensor by 3 degrees
      value_template: >
        {% if states('sensor.broadlink_sensor_temperature') %}
        {{  states('sensor.broadlink_sensor_temperature') | float - 3 }}
        {% else %}
        0.0
        {% endif %}

    presence:
      value_template: >
        {% if states('alarm_control_panel.home_alarm') == 'armed_home' or states('alarm_control_panel.home_alarm') == 'armed_night'%}
        Yes
        {% else %}
        No
        {% endif %}

    sleeping:
      value_template: >
        {% if states('alarm_control_panel.home_alarm') == 'armed_night' %}
        Yes
        {% else %}
        No
        {% endif %}



#- platform: n26
#  username: !secret n26_username
#  password: !secret n26_password
#  currency: EUR