- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary
    - temperature_min
    - temperature_max
  update_interval: '00:15'

- platform: minecraft
  name: Minecraft
  server: !secret minecraft_server

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  monitored_conditions:
    - temperature

- platform: template
  sensors:
    inside_temperature:
      value_template: "{{  states.sensor.broadlink_sensor_temperature.state | float - 3 }}" # offset broadlink by 3ËšC

