- platform: buienradar
  monitored_conditions:
    - condition
    - humidity
    - temperature
    - windspeed
    - precipitation
    - precipitation_forecast_total

- platform: miflora
  mac: 'C4:7C:8D:66:42:FC'

- platform: serial_pm
  serial_device: /dev/ttyUSB0
  name: Particle Sensor
  brand: novafitness,sds011

- platform: waqi
  token: !secret waqi_token
  locations:
    - utrecht
  stations:
    - de Jongweg
