- platform: buienradar
  monitored_conditions:
    - condition
    - humidity
    - temperature
    - pressure
    - precipitation
    - precipitation_forecast_total


- platform: miflora
  mac: 'C4:7C:8D:66:42:FC'

#- platform: serial_pm#  serial_device: /dev/ttyUSB0
#  name: Particle Sensor
#  brand: novafitness,sds011

- platform: waqi
  token: !secret waqi_token
  locations:
    - 'utrecht'
  stations:
    - 'de Jongweg, Utrecht'

# Templates
- platform: template
  sensors:
    air_quality_status:
      friendly_name: Air Quality Status
      value_template: >
        {% if states('sensor.waqi_de_jongweg_utrecht') | int <= 50 %}
          Good
        {% elif states('sensor.waqi_de_jongweg_utrecht') | int <= 100 %}
          Moderate
        {% elif states('sensor.waqi_de_jongweg_utrecht') | int <= 150 %}
          Unhealthy for Sensitive Groups
        {% elif states('sensor.waqi_de_jongweg_utrecht') | int <= 200 %}
          Unhealthy
        {% elif states('sensor.waqi_de_jongweg_utrecht') | int <= 300 %}
          Very Unhealthy
        {% elif states('sensor.waqi_de_jongweg_utrecht') | int > 300 %}
          Hazardous
        {% else %}
          Unknown
        {% endif %}

    plant_emoji:
      friendly_name: "Plant"
      value_template: > 
        {% if is_state('plant.plant', 'ok') %}
          Perfect
        {% elif is_state('plant.plant', 'unknown') %}
          Unknown
        {% else %}
          {{ states.plant.plant.attributes.problem }}
        {% endif %}
      icon_template: >
        {% if is_state('sensor.plant_emoji', 'perfect') %}
          mdi:emoticon-happy
        {% elif is_state('sensor.plant_emoji', 'unkown') %}
          mdi:help-circle
        {% elif states('sensor.plant_emoji').split(',') | length == 1  %}
          mdi:emoticon-neutral
        {% else %}
          mdi:emoticon-sad
        {% endif %}

    status_summary:
      friendly_name: Status Summary
      value_template: >
        {% if is_state("group.roman", "home") and is_state("group.nadine", "home") -%}
          Roman and Nadine are
        {%- elif is_state("group.roman", "home") -%}
          Roman is
        {%- elif is_state("group.nadine", "home") -%}
          Nadine is
        {%- else -%}
          No one is home. {%- endif -%}
        {%- if (is_state("group.roman", "home") or is_state("group.nadine", "home")) and is_state("switch.television", "on") -%}
          {{ " " }}watching television.
        {%- elif (is_state("group.roman", "home") or is_state("group.nadine", "home")) and is_state("input_select.home_status", "Night") -%}
          {{ " " }}in bed.
        {%- else -%}
           {{ " " }}home.{%- endif -%}
        {%- if is_state("climate.thermostat", "idle") -%}
          {{ " " }}The thermostat is set to {{ states.climate.thermostat.attributes.temperature }} °C.
        {%- elif is_state("climate.thermostat", "heat") -%}
          {{ " " }}The thermostat is heating to {{ states.climate.thermostat.attributes.temperature }} °C.
        {%- endif -%}
        {%- if is_state("binary_sensor.door", "on") -%}
          {{ " " }}The door is open.
        {%- endif %}
        {%- for i in states.group.status.attributes.entity_id if is_state(i, 'on') -%}
          {%- if loop.first %}{{ " " }}The {% elif loop.last %} and the {% else %}, the {% endif -%}
          {{ state_attr(i, 'friendly_name') | lower }} is {{ states(i) }}
          {%- if loop.last %}.{% endif -%}
        {%- endfor -%}
        {%- if is_state("group.status", "off") and (is_state("climate.thermostat", "heat") or is_state("climate.thermostat", "idle") or is_state("switch.television", "on")) -%}
          {{ " " }}All other devices are off.
        {%- else -%}
          {{ " " }}All devices are off.
        {%- endif %}
### MQTT

- platform: "mqtt"
  name: Button
  state_topic: "zigbee2mqtt/button"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
    - "battery"
    - "voltage"
    - "action"
    - "duration"

- platform: "mqtt"
  name: Wall switch
  state_topic: "zigbee2mqtt/wall_switch"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
    - "battery"
    - "voltage"
    - "action"
    - "duration"

- platform: "mqtt"
  name: Xiaomi Temperature
  state_topic: "zigbee2mqtt/sensor_inside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"
  value_template: "{{ value_json.temperature }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Xiaomi Humidity
  state_topic: "zigbee2mqtt/sensor_inside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Xiaomi Pressure
  state_topic: "zigbee2mqtt/sensor_inside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  icon: "mdi:speedometer"
  value_template: "{{ value_json.pressure }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Xiaomi Temperature 2
  state_topic: "zigbee2mqtt/sensor_outside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"
  value_template: "{{ value_json.temperature }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Xiaomi Humidity 2
  state_topic: "zigbee2mqtt/sensor_outside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Xiaomi Pressure 2
  state_topic: "zigbee2mqtt/sensor_outside"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  icon: "mdi:speedometer"
  value_template: "{{ value_json.pressure }}"
  json_attributes: 
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: Illuminance
  state_topic: "zigbee2mqtt/motion_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  icon: "mdi:theme-light-dark"
  value_template: "{{ value_json.illuminance }}"
  json_attributes: 
    - "battery"
    - "voltage"

#- platform: "mqtt"
#  name: Camera Light Sensor
#  state_topic: xiaomi/dafang/brightness
#  icon: mdi:brightness-5
#  unit_of_measurement: "%"

#- platform: "mqtt"
#  name: Camera
#  state_topic: xiaomi/dafang
#  icon: "mdi:cctv"
#  json_attributes: 
#    - uptime
#    - load average
#    - ssid
#    - bitrate
#    - signal_level 
#    - link_quality
#    - noise_level


# my sonoff th 10 broke :/
#- platform:  "mqtt"
#  name: "Sonoff Temperature"
#  state_topic: "sonoff_th10/sensor/thermostat_temperature/state"
#  availability_topic: "sonoff_th10/status"
#  unit_of_measurement: "°C"
#  expire_after: 675

#- platform:  "mqtt"
#  name: "Sonoff Humidity"
#  icon: mdi:water-percent
#  state_topic: "sonoff_th10/sensor/thermostat_humidity/state"
#  availability_topic: "sonoff_th10/status"
#  unit_of_measurement: "%"
#  expire_after: 675

