- platform: broadlink
  host: "192.168.1.2"
  mac: "b4:43:0d:db:97:6c"
  type: mp1
  friendly_name: Power Strip
  slots:
     slot_1: A
     slot_2: B
     slot_3: C
     slot_4: D

- platform: broadlink
  host: "192.168.1.3"
  mac: "b4:43:0d:db:97:6c"
  type: rm2_pro_plus
  switches:
    sony:
      friendly_name: Television
      command_on: "JgBsAU4UJRYSFSUVEhUkFxEWEhQmFRAXExMRFRIAA1FMFiYWDhgkFxEVKBUOFxEWJhQSFRAXEBYSAANRTRUmFREWJRYSFCQXERURFiQXEhcPFREVEgADUU0WJRYRFSQZDhYnFBMUERYkFxIVERYQFg8AA1NLFicVEBcmFBIWJRYQFhEVIxoOFxAWEhQSAANRTRUoFA8XJRYRFScUExQRFiUVFBMRFhEVEgADUUwWJBcRFiYVDhglFhEVEhUnFRAVERYRFhEAA1FNFSYVEhUlFhEVJhURFhEVJhURFhEVEhURAANSTRQmFRIVJhUSFSUWERURFiUWERURFhEVEgADUU0WJRYQFSYVEhUmFREWERUmFREWEhQRFxAAA1JMFSYVEhUmFREVJhUSFREWJRYRFREWERURAANSTRUlFhEVJhUSFSYVERYRFSYVERYRFREWEQADUkwVJhUSFSYVERUmFRIVERYlFhEVERYRFREADQUAAAAAAAAAAAAAAAA"
      command_off: "JgBsAU4UJRYSFSUVEhUkFxEWEhQmFRAXExMRFRIAA1FMFiYWDhgkFxEVKBUOFxEWJhQSFRAXEBYSAANRTRUmFREWJRYSFCQXERURFiQXEhcPFREVEgADUU0WJRYRFSQZDhYnFBMUERYkFxIVERYQFg8AA1NLFicVEBcmFBIWJRYQFhEVIxoOFxAWEhQSAANRTRUoFA8XJRYRFScUExQRFiUVFBMRFhEVEgADUUwWJBcRFiYVDhglFhEVEhUnFRAVERYRFhEAA1FNFSYVEhUlFhEVJhURFhEVJhURFhEVEhURAANSTRQmFRIVJhUSFSUWERURFiUWERURFhEVEgADUU0WJRYQFSYVEhUmFREWERUmFREWEhQRFxAAA1JMFSYVEhUmFREVJhUSFREWJRYRFREWERURAANSTRUlFhEVJhUSFSYVERYRFSYVERYRFREWEQADUkwVJhUSFSYVERUmFRIVERYlFhEVERYRFREADQUAAAAAAAAAAAAAAAA"


#      up: "JgCMAE0WERUPFyYWEhQkFyUXJhQnFA8YEhQTExIAAz1LFxMTEBclFxITJxQlFyQXJxQPFxIVERUSAAM8TBcSFBAXJxMRFiQXJRclFSUWEhQTFBAWFAADO0sWExQQFycUERUkFyYVJxQmFREXERQQFxIAAzxOFBEVEhYmFBAXJRclFSYVJRYQFxEVEBcSAA0FAAAAAAAAAAAAAAAA"
#      down: "JgAYAU4UJhUSFSUWEBYmFSYVJxQnFBMUEhQRFhEAAylMFiUWEhQmFREWJRYmFSYVJhUTExMUEBcSAAMnThQmFRIVJRYRFSYVJhUnFCcUEhUSFBEWEQADKU0VJhUQFicUEhUmFSUWJhUmFREWERURFhEAAyhNFSYVERYlFhEVJRYnFCcUJxQSFREVERYSAAMoTRUmFRAWJhUTFCYVJRYnFCYVERYRFREWEgADJ04UJhURFiUWEhQlFicUJhUmFREWEhQRFhEAAylNFSYVEBYnFBMUJRYlFiYVJhURFhEVERYRAAMoTRUmFRIVJRYRFSUWJhUmFScUERYSFBEWEQADKU0VJhUQFicUEhUmFSUWKBMnFBEWERURFhEADQU="



- platform: xiaomi_miio
  name: E
  host: "192.168.1.5"
  token: !secret xiaomi_plug_token
  model: chuangmi.plug.m1
