- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1
  friendly_name: Power strip
  slots:
     slot_1: Fan
     slot_2: 'Air purifier'
     slot_3: TV
     slot_4: Speakers

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac

#- platform: template
#  switches:
#    tv:
#      friendly_name: 'Television'
#      value_template: "{{ is_state('states.switch.g', 'on')  }}"
#      turn_on:
#        service: script.tv_on
#      turn_off:
#        service: script.tv_off

- platform: command_line
  switches:
    update_from_github:
      friendly_name: 'Update config'
      command_on: "home/roman/.homeassistant/other/git_update.sh"
