- platform: broadlink
  host: "10.10.10.202"
  mac: "b4:43:0d:db:97:6c"
  type: mp1
  friendly_name: Power Strip
  slots:
     slot_1: Speakers
     slot_2: Television
     slot_3: Fan
     slot_4: Socket

- platform: broadlink
  host: "10.10.10.203"
  mac: "b4:43:0d:db:97:6c"
  type: rm2_pro_plus
#  switches:
#    sony:
#      friendly_name: Television
#      command_on: "JgBsAU4UJRYSFSUVEhUkFxEWEhQmFRAXExMRFRIAA1FMFiYWDhgkFxEVKBUOFxEWJhQSFRAXEBYSAANRTRUmFREWJRYSFCQXERURFiQXEhcPFREVEgADUU0WJRYRFSQZDhYnFBMUERYkFxIVERYQFg8AA1NLFicVEBcmFBIWJRYQFhEVIxoOFxAWEhQSAANRTRUoFA8XJRYRFScUExQRFiUVFBMRFhEVEgADUUwWJBcRFiYVDhglFhEVEhUnFRAVERYRFhEAA1FNFSYVEhUlFhEVJhURFhEVJhURFhEVEhURAANSTRQmFRIVJhUSFSUWERURFiUWERURFhEVEgADUU0WJRYQFSYVEhUmFREWERUmFREWEhQRFxAAA1JMFSYVEhUmFREVJhUSFREWJRYRFREWERURAANSTRUlFhEVJhUSFSYVERYRFSYVERYRFREWEQADUkwVJhUSFSYVERUmFRIVERYlFhEVERYRFREADQUAAAAAAAAAAAAAAAA"
#      command_off: "JgBsAU4UJRYSFSUVEhUkFxEWEhQmFRAXExMRFRIAA1FMFiYWDhgkFxEVKBUOFxEWJhQSFRAXEBYSAANRTRUmFREWJRYSFCQXERURFiQXEhcPFREVEgADUU0WJRYRFSQZDhYnFBMUERYkFxIVERYQFg8AA1NLFicVEBcmFBIWJRYQFhEVIxoOFxAWEhQSAANRTRUoFA8XJRYRFScUExQRFiUVFBMRFhEVEgADUUwWJBcRFiYVDhglFhEVEhUnFRAVERYRFhEAA1FNFSYVEhUlFhEVJhURFhEVJhURFhEVEhURAANSTRQmFRIVJhUSFSUWERURFiUWERURFhEVEgADUU0WJRYQFSYVEhUmFREWERUmFREWEhQRFxAAA1JMFSYVEhUmFREVJhUSFREWJRYRFREWERURAANSTRUlFhEVJhUSFSYVERYRFSYVERYRFREWEQADUkwVJhUSFSYVERUmFRIVERYlFhEVERYRFREADQUAAAAAAAAAAAAAAAA"

#      up: "JgCMAE0WERUPFyYWEhQkFyUXJhQnFA8YEhQTExIAAz1LFxMTEBclFxITJxQlFyQXJxQPFxIVERUSAAM8TBcSFBAXJxMRFiQXJRclFSUWEhQTFBAWFAADO0sWExQQFycUERUkFyYVJxQmFREXERQQFxIAAzxOFBEVEhYmFBAXJRclFSYVJRYQFxEVEBcSAA0FAAAAAAAAAAAAAAAA"
#      down: "JgAYAU4UJhUSFSUWEBYmFSYVJxQnFBMUEhQRFhEAAylMFiUWEhQmFREWJRYmFSYVJhUTExMUEBcSAAMnThQmFRIVJRYRFSYVJhUnFCcUEhUSFBEWEQADKU0VJhUQFicUEhUmFSUWJhUmFREWERURFhEAAyhNFSYVERYlFhEVJRYnFCcUJxQSFREVERYSAAMoTRUmFRAWJhUTFCYVJRYnFCYVERYRFREWEgADJ04UJhURFiUWEhQlFicUJhUmFREWEhQRFhEAAylNFSYVEBYnFBMUJRYlFiYVJhURFhEVERYRAAMoTRUmFRIVJRYRFSUWJhUmFScUERYSFBEWEQADKU0VJhUQFicUEhUmFSUWKBMnFBEWERURFhEADQU="

- platform: xiaomi_miio
  name: Air Purifier
  host: "10.10.10.205"
  token: !secret xiaomi_plug_token
  model: chuangmi.plug.m1

- platform: mqtt
  name: Coffee maker
  icon: "mdi:coffee"
  state_topic: "sonoff/switch/coffee_maker/state"
  command_topic: "sonoff/switch/coffee_maker/command"
  availability_topic: "sonoff/status"
