- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1-1
  friendly_name: E
- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1-2
  friendly_name: F
- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1-3
  friendly_name: G
- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1-4
  friendly_name: H

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac

#- platform: template
#  switches:
#    tv:
#      friendly_name: 'Television'
#      value_template: "{{ is_state('states.switch.g', 'on')  }}"
#      turn_on:
#        service: script.tv_on
#      turn_off:
#        service: script.tv_off

- platform: command_line
  switches:
    update_from_github:
      friendly_name: 'Update config'
      command_on: "home/roman/.homeassistant/other/git_update.sh"
