- platform: broadlink
  host: "10.10.10.202"
  mac: "b4:43:0d:db:97:6c"
  type: mp1
  friendly_name: Power Strip
  slots:
     slot_1: Entone
     slot_2: Socket behind TV  # For future use
     slot_3: Television
     slot_4: Speakers

- platform: broadlink
  host: "10.10.10.203"
  mac: "b4:43:0d:db:97:6c"
  type: rm2_pro_plus
  switches:
    socket_1:
      friendly_name: "Socket 1"
      command_on: "sg0yAAcRBhESBgYRBhEGEQYREgYRBgYRBhEGrREGBhEGEQYRBxERBgYREQYSBgYREQYRBgYRAAAAAAAA"
      command_off: "sg8yAAYREgYGERIGEgYGEhEGEgYGEQYRBhERBgYRBhEGEQYRBhEGEREGBhEGrBEGBhEGEQYRAAAAAAAA"
    socket_2:
      friendly_name: "Socket 2"
      command_on: "sgsyAAYSBhEHEQcREQcGEhEGBxEGrREGBhIGEQYRBhERBgYSEQYRBgcREQYRBwYRBhEGEREHAAAAAAAA"
      command_off: "skcyABEGBhEGEQYRBhESBgYREQYRBgcREgYSBgYRBhEHEREGBhEGEQYRBhEGEQYREgYGEQasAAAAAAAA"
    socket_3:
      friendly_name: "Socket 3"
      command_on: "sgoyABIGBxEHEQcRBhESBgcREgYSBQcREgUSBgcRBxEHERIFBxEGEQcRBhESBgcRBhESBgesAAAAAAAA"
      command_off: "sgYyAAasEQYHEQYRBxEGEREGBhESBhEGBhERBhIGBhEGEgYSEQYGEQYRBhEGEQYRBhEGEREGAAAAAAAA"
    fan:  # socket 4
      friendly_name: "Fan"
      command_on: "sgsyABIGEQYGEREGEgYGEQcRBhERBgYRBxEGEQcREgYSBgcREgYGrBEGBxEGEQYRBxESBgcRAAAAAAAA"
      command_off: "sgoyABEGBhEGEQYREQYGEQYRBhEGEQcREQYGERIGBqwRBgYRBhEGEQYREQYGERIGEQYGEREGAAAAAAAA"
    air_purifier:  # socket 5
      friendly_name: "Air Purifier"
      command_on: "sg4yABIGBhEGEQYRBhIRBgYREQYRBgYREQYRBgYRBhIGEREGBhEGEQYRBhERBgYREQYRBgasAAAAAAAA"
      command_off: "shEyABIGBhEGEQYRBhERBgYREQYRBgYREQYRBgYRBhEHEREGBhEGEQYRBxEHEQYREQYRBgesAAAAAAAA"

# Unused at this time
#- platform: xiaomi_miio
#  name: Socket
#  host: "10.10.10.204"
#  token: !secret xiaomi_plug_token
#  model: chuangmi.plug.m1

- platform: mqtt
  name: Coffee Maker
  icon: "mdi:coffee"
  state_topic: "sonoff/switch/coffee_maker/state"
  command_topic: "sonoff/switch/coffee_maker/command"
  availability_topic: "sonoff/status"

- platform: mqtt
  name: Air Freshener
  icon: "mdi:wind"
  state_topic: "nodemcu_amica/switch/air_freshener/state"
  command_topic: "nodemcu_amica/switch/air_freshener/command"
  availability_topic: "nodemcu_amica/status"

- platform: mqtt
  name: Camera H264
  icon": mdi:cctv
  state_topic: xiaomi/dafang/rtsp_h264_server
  command_topic: xiaomi/dafang/rtsp_h264_server/set

- platform: mqtt
  name: Camera MJPEG
  icon: mdi:cctv
  state_topic: xiaomi/dafang/rtsp_mjpeg_server
  command_topic: xiaomi/dafang/rtsp_mjpeg_server/set

- platform: mqtt
  name: Camera IR Filter
  icon: mdi:image-filter-black-white
  state_topic: xiaomi/dafang/ir_cut
  command_topic: xiaomi/dafang/ir_cut/set

- platform: mqtt
  name: Camera IR LED
  icon: mdi:weather-night
  state_topic: xiaomi/dafang/leds/ir
  command_topic: xiaomi/dafang/leds/ir/set

- platform: mqtt
  name: Camera Night Mode
  icon: mdi:weather-night
  state_topic: xiaomi/dafang/night_mode
  command_topic: xiaomi/dafang/night_mode/set

- platform: mqtt
  name: Camera Night Mode Auto
  icon: mdi:weather-night
  state_topic: xiaomi/dafang/night_mode/auto
  command_topic: xiaomi/dafang/night_mode/auto/set

- platform: mqtt
  name: Camera Blue LED
  icon: mdi:led-on
  state_topic: xiaomi/dafang/leds/blue
  command_topic: xiaomi/dafang/leds/blue/set

- platform: mqtt
  name: Camera Yellow LED
  icon: mdi:led-on
  state_topic: xiaomi/dafang/leds/yellow
  command_topic: xiaomi/dafang/leds/yellow/set

- platform: mqtt
  name: Camera Motion Detection
  icon: mdi:run
  state_topic: xiaomi/dafang/motion/detection
  command_topic: xiaomi/dafang/motion/detection/set

- platform: mqtt
  name: Camera Motion Tracking
  icon: mdi:run
  state_topic: xiaomi/dafang/motion/tracking
  command_topic: xiaomi/dafang/motion/tracking/set  

- platform: mqtt
  name: zigbee2mqtt pairing
  icon: mdi:cellphone-wireless
  command_topic: zigbee2mqtt/bridge/config/permit_join
  payload_on: "true"
  payload_off: "false"

