- platform: broadlink
  host: "10.10.10.202"
  mac: "b4:43:0d:db:97:6c"
  type: mp1
  friendly_name: Power Strip
  slots:
     slot_1: Entone
     slot_2: Air Purifier
     slot_3: Television
     slot_4: Socket

- platform: broadlink
  host: "10.10.10.203"
  mac: "b4:43:0d:db:97:6c"
  type: rm2_pro_plus
  switches:
    socket_1:
      friendly_name: "Socket 1"
      command_on: "sg0yAAcRBhESBgYRBhEGEQYREgYRBgYRBhEGrREGBhEGEQYRBxERBgYREQYSBgYREQYRBgYRAAAAAAAA"
      # command_off is broken
      command_off: "sg8yAAYREgYGERIGEgYGEhEGEgYGEQYRBhERBgYRBhEGEQYRBhEGEREGBhEGrBEGBhEGEQYRAAAAAAAA"
    spot:
      friendly_name: "Spot"
      command_on: "sgsyAAYSBhEHEQcREQcGEhEGBxEGrREGBhIGEQYRBhERBgYSEQYRBgcREQYRBwYRBhEGEREHAAAAAAAA"
      command_off: "skcyABEGBhEGEQYRBhESBgYREQYRBgcREgYSBgYRBhEHEREGBhEGEQYRBhEGEQYREgYGEQasAAAAAAAA"
    camera:
      friendly_name: "Camera"
      command_on: "sgoyABIGBxEHEQcRBhESBgcREgYSBQcREgUSBgcRBxEHERIFBxEGEQcRBhESBgcRBhESBgesAAAAAAAA"
      command_off: "sgYyAAasEQYHEQYRBxEGEREGBhESBhEGBhERBhIGBhEGEgYSEQYGEQYRBhEGEQYRBhEGEREGAAAAAAAA"
    socket_4:  # socket 4
      friendly_name: "Fan"
      command_on: "sgsyABIGEQYGEREGEgYGEQcRBhERBgYRBxEGEQcREgYSBgcREgYGrBEGBxEGEQYRBxESBgcRAAAAAAAA"
      command_off: "sgoyABEGBhEGEQYREQYGEQYRBhEGEQcREQYGERIGBqwRBgYRBhEGEQYREQYGERIGEQYGEREGAAAAAAAA"
    socket_5:  # socket 5
      friendly_name: "Socket 5"
      command_on: "sg4yABIGBhEGEQYRBhIRBgYREQYRBgYREQYRBgYRBhIGEREGBhEGEQYRBhERBgYREQYRBgasAAAAAAAA"
      command_off: "shEyABIGBhEGEQYRBhERBgYREQYRBgYREQYRBgYRBhEHEREGBhEGEQYRBxEHEQYREQYRBgesAAAAAAAA"

- platform: mqtt
  name: Coffee Maker
  icon: "mdi:coffee"
  state_topic: "sonoff/switch/coffee_maker/state"
  command_topic: "sonoff/switch/coffee_maker/command"
  availability_topic: "sonoff/status"

- platform: mqtt
  name: Heater
  icon: "mdi:radiator-disabled"
  state_topic: "sonoff2/switch/heater/state"  # "sonoff_th10/switch/heater/state"
  command_topic: "sonoff2/switch/heater/command"  # "sonoff_th10/switch/heater/command"
  availability_topic: "sonoff2/status"  # "sonoff_th10/status"

- platform: mqtt
  name: zigbee2mqtt pairing
  icon: mdi:cellphone-wireless
  command_topic: zigbee2mqtt/bridge/config/permit_join
  payload_on: "true"
  payload_off: "false"

