#Home Assistant switches
- platform: broadlink
  host: !secret broadlinkmp1_ip
  mac: !secret broadlinkmp1_mac
  type: mp1
  friendly_name: Power strip
  slots:
     slot_1: Fan
     slot_2: Air purifier
     slot_3: Television
     slot_4: Speakers

