name: Home
views:
  - title: Dashboard
    tab_icon: mdi:home
    background: center / cover no-repeat url("/local/images/background_blur.jpg") fixed
    cards:
      - !include 'lovelace/topdown_vertical.yaml'
      - !include 'lovelace/lights.yaml'
      - !include 'lovelace/media_player.yaml'
      - !include 'lovelace/appliances.yaml'
      - !include 'lovelace/coffee_maker.yaml'
      - !include 'lovelace/environment.yaml'
      - !include 'lovelace/activity.yaml'
      - !include 'lovelace/graphs.yaml'
      - !include 'lovelace/plant.yaml'
      - !include 'lovelace/camera.yaml'


  - title: Testing
    tab_icon: mdi:flask
    background: center / cover no-repeat url("/local/images/background_blur.jpg") fixed
    cards: !include 'lovelace/views/testing.yaml'

  - title: Room
    tab_icon: mdi:home
    panel: true
    cards:
      - !include 'lovelace/topdown_horizontal.yaml'

  - title: Camera
    tab_icon: mdi:eye
    panel: true
    cards:
      - !include 'lovelace/camera_extended.yaml'

  - title: Remote
    tab_icon: mdi:remote
    theme: remote
    panel: true
    cards:
      - !include 'lovelace/remote.yaml'
