name: Home
resources:
  - url: /local/mini-media-player/mini-media-player.js
    type: js
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1
    type: module
views:
### VIEW 1
  - id: 0  # Automatically created id
    title: Control
    tab_icon: mdi:home
    background: center / cover no-repeat url("/local/images/background_blur.jpg")
      fixed
    cards:
# LIGHTS
      - type: entities
        id: b0e3b0e36a9a4deba2b93ba14ef47001  # Automatically created id
        show_header_toggle: false
        entities:
          - light.standing_lamp
          - switch.spot
          - light.ceiling_lamp
          - group.led_strips
          - light.tv_backlight
        theme: Backend-selected
      - id: a028535ccd4e4ec498559ccc9a96eb89  # Automatically created id
        type: horizontal-stack
        cards:
          - type: entity-button
            name: Air
            tap_action: toggle
            hold_action: more-info
            entity:
              - switch.air_purifier
          - type: entity-button
            name: Coffee
            tap_action: toggle
            hold_action: more-info
            entity:
              - switch.coffee_maker
          - type: entity-button
            name: Television
            tap_action: toggle
            hold_action: more-info
            entity:
              - switch.television

# REMOTE MINI
      - id: 93431bdc4fa94b12bf1e6901fcfbf3fe  # Automatically created id
        type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: switch.television
                state: "on"
            card:
              type: picture-elements
              image: /local/images/white.jpg
              elements:
                - type: state-icon
                  entity: switch.television
                  tap_action: toggle
                  style:
                    top: 10%
                    left: 10%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: switch.entone
                  tap_action: toggle
                  style:
                    top: 10%
                    left: 30%
                    outline-style: solid
                    outline-width: 1px
                    text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px white
                    outline-color: grey
                - type: state-label
                  entity: input_select.tv_input
                  style:
                    top: 10%
                    left: 60%
                - type: state-icon
                  entity: light.tv_backlight
                  tap_action: toggle
                  style:
                    top: 30%
                    left: 10%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.input_up
                  tap_action: call-service
                  service: script.turn_on
                  style:
                    top: 10%
                    left: 90%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.input_down
                  tap_action: call-service
                  service: script.turn_on
                  style:
                    top: 30%
                    left: 90%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.sony_theatre
                  tap_action: toggle
                  style:
                    top: 30%
                    left: 30%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.apple_up
                  tap_action: toggle
                  style:
                    top: 30%
                    left: 50%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.apple_left
                  tap_action: toggle
                  style:
                    top: 50%
                    left: 30%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-label
                  entity: switch.television
                  style:
                    top: 50%
                    left: 50%
                - type: state-icon
                  entity: script.apple_ok
                  tap_action: toggle
                  style:
                    top: 70%
                    left: 70%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.apple_right
                  tap_action: toggle
                  style:
                    top: 50%
                    left: 70%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.apple_back
                  tap_action: toggle
                  style:
                    top: 70%
                    left: 30%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.apple_down
                  tap_action: toggle
                  style:
                    top: 70%
                    left: 50%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.sony_mute
                  tap_action: toggle
                  style:
                    top: 90%
                    left: 10%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.sony_volume_lower
                  tap_action: toggle
                  style:
                    top: 90%
                    left: 30%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.sony_volume_higher
                  tap_action: toggle
                  style:
                    top: 90%
                    left: 50%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.entone_channel_down
                  tap_action: toggle
                  style:
                    top: 90%
                    left: 70%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey
                - type: state-icon
                  entity: script.entone_channel_up
                  tap_action: toggle
                  style:
                    top: 90%
                    left: 90%
                    outline-style: solid
                    outline-width: 1px
                    outline-color: grey

# MEDIA PLAYER
          - type: conditional
            conditions:
              - entity: input_select.tv_input
                state: "Apple TV"
            card:
              type: custom:mini-media-player
              entity: media_player.apple_tv

# THERMOSTAT
      - id: 94388c17d89a4575a995a0cb181a5166  # Automatically created id
        type: custom:thermostat-card
        entity: climate.thermostat

### VIEW 2
  - id: 1  # Automatically created id
    title: Status
    background: center / cover no-repeat url("/local/images/background_blur.jpg")
      fixed
    cards:

# PERSONS
      - id: 53ca9509f43e4e70a4149595b70533d7  # Automatically created id
        type: entities
        entities:
          - group.roman
#          - group.nadine
          - group.laurens
          - group.nikki


# GRAPHS
      - id: f0ed4b3909ee45248717c962735db826  # Automatically created id
        type: history-graph
        entities:
          - sensor.xiaomi_temperature
          - sensor.br_temperature
          - sensor.mi_flora_temperature

# PLANT
      - id: 640393e6744847de897efc1bc1189eca  # Automatically created id
        type: plant-status
        entity: plant.plant

### VIEW 3
  - id: 2  # Automatically created id
    title: Settings
    background: center / cover no-repeat url("/local/images/background_blur.jpg")
      fixed
    cards:
      - id: a0f1fcd3c96f4debaa762ab298d0f419  # Automatically created id
        type: entities
        entities:
          - input_select.home_status
