devices:
  '0x00158d0001b958bc':
    friendly_name: door_sensor
    retain: false
  '0x00158d0001de85f7':
    friendly_name: motion_sensor
    occupancy_timeout: 3
    retain: false
  '0x00158d0001e11783':
    friendly_name: wall_switch
    retain: false
  '0x00158d0001f4b7af':
    friendly_name: button
    retain: false
  '0x00158d00022c8d56':
    friendly_name: sensor
    retain: true
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://homeassistant
permit_join: false
serial:
  port: /dev/ttyACM0
