binary_sensor:
  - platform: template
    sensors:
      kitchen_occupancy:
        friendly_name: "Kitchen Occupancy"
        value_template: "{{ is_state('input_boolean.kitchen_occupancy', 'on')}}"
        icon_template: mdi:microwave

input_boolean:
  kitchen_occupancy:
    name: Kitchen Occupancy

automation:
# Turn On
  - id: kitchen_occupancy_on
    alias: Kitchen Occupancy On
    trigger:
      - platform: state
        entity_id: binary_sensor.xiaomi_motion_sensor
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_occupancy

# Turn Off
  - id: kitchen_occupancy_off
    alias: Kitchen Occupancy Off
    trigger:
      - platform: state
        entity_id: binary_sensor.xiaomi_motion_sensor
        to: 'off'
        for:
          seconds: 90
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_occupancy
