
binary_sensor:
  - platform: template
    sensors:
      window_tilt_draft:
        friendly_name: "Window Tilt Draft"
        value_template: >-
          {% if is_state('binary_sensor.window_tilt', 'on') and
                  state_attr('weather.home', 'wind_speed')|float > 40 %}
            true
          {% else %}
            false
          {% endif %}

automation:
  - id: shade_closes_while_window_open
    alias: Shade Closes While Window Open
    mode: "restart"
    trigger:
      - platform: numeric_state
        entity_id: cover.ikea_fyrtur_2
        value_template: "{{ state.attributes.current_position }}"
        below: 100
    condition:
      - condition: state
        entity_id: binary_sensor.xiaomi_contact_sensor_3
        state:  'on'
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.ikea_fyrtur_2
      - wait_template: "{{ is_state('binary_sensor.xiaomi_contact_sensor_3', 'off') }}"
      - service: cover.close_cover
        data:
          entity_id: cover.ikea_fyrtur_2

  - id: shade_opens_while_window_open
    alias: Shade Closes While Window Open
    mode: "restart"
    trigger:
      - platform: numeric_state
        entity_id: cover.ikea_fyrtur_2
        value_template: "{{ state.attributes.current_position }}"
        above: 0
    condition:
      - condition: state
        entity_id: binary_sensor.window_tilt_draft
        state:  'on'
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.ikea_fyrtur_2
      - wait_template: "{{ is_state('binary_sensor.window_tilt_draft', 'off') }}"
      - service: cover.open_cover
        data:
          entity_id: cover.ikea_fyrtur_2
