input_select:
  home_status:
    name: Home Status
    options:
      - 'Home'
      - 'Night'
      - 'Away'
      - 'Off'

sensor:
  - platform: template
    sensors:
      home_status:
        friendly_name: "Home Status"
        value_template: >-
          {{ states("input_select.home_status") }}
        icon_template: >-
          {% if is_state('input_select.home_status', 'Home') %}
            mdi:home-account
          {% elif is_state('input_select.home_status', 'Night') %}
            mdi:weather-night
          {% elif is_state('input_select.home_status', 'Away') %}
            mdi:home
          {% elif is_state('input_select.home_status', 'Off') %}
            mdi:power-off
          {% endif %}
