automation:
  - id: home_status_to_off
    alias: Home Status to Off
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Off'
    action:
      - service: automation.turn_off
        entity_id: group.home_status_automations
  
  - id: home_status_from_off
    alias: Home Status from Off
    trigger:
      - platform: state
        entity_id: input_select.home_status
        from: 'Off'
    action:
      - service: automation.turn_on
        entity_id: group.home_status_automations

