automation:
  - id: home_status_to_home_from_away
    alias: Home Status to Home from Away
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: Home
        from: Away
    action:
      - service: switch.turn_off
        entity_id: switch.air_purifier
      - service: switch.turn_on
        entity_id: switch.chromecast
  
  - id: home_status_to_home_from_away_during_sunset
    alias: Home Status to Home from Away during Sunset
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: Home
        from: Away
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:15:00"
        - condition: sun
          before: sunrise
    action:
      - service: python_script.sunset
  
  - id: home_status_to_home_from_away_at_night_time
    alias: Home Status to Home from Away at night time
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: Home
        from: Away
    condition:
      condition: or  # 'when dark' condition either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.evening
  
  
