automation:
  - id: home_status_to_night
    alias: Home Status to Night
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: Night
    action:
      - service: light.turn_off
        entity_id: group.all_lights
