binary_sensor:
  - platform: rest
    resource: http://10.10.10.10:8126/container/addon_a0d7b954_foldingathome
    method: GET
    name: Folding
    value_template: '{{ value_json is not none and value_json.state == "running" }}'

switch:
  - platform: template
    switches:
      folding:
        value_template: "{{ is_state('binary_sensor.folding', 'on') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_foldingathome
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_foldingathome

homeassistant:
  customize:
    switch.folding:
      icon: mdi:cogs
