cover:
  - platform: mqtt
    name: IKEA Fyrtur
    command_topic: zigbee2mqtt/ikea_fyrtur/set
    position_topic: zigbee2mqtt/ikea_fyrtur
    set_position_topic: zigbee2mqtt/ikea_fyrtur/set
    value_template: "{{ value_json.position }}"
    set_position_template: "{ \"position\": {{ position }} }"

  - platform: mqtt
    name: IKEA Fyrtur 2
    command_topic: zigbee2mqtt/ikea_fyrtur_2/set
    position_topic: zigbee2mqtt/ikea_fyrtur_2
    set_position_topic: zigbee2mqtt/ikea_fyrtur_2/set
    value_template: "{{ value_json.position }}"
    set_position_template: "{ \"position\":{{ position }} }"
  
  - platform: mqtt
    name: IKEA Fyrtur 3
    command_topic: zigbee2mqtt/ikea_fyrtur_3/set
    position_topic: zigbee2mqtt/ikea_fyrtur_3
    set_position_topic: zigbee2mqtt/ikea_fyrtur_3/set
    value_template: "{{ value_json.position }}"
    set_position_template: "{ \"position\":{{ position }} }"

  - platform: group
    name: Covers
    entities:
      - cover.ikea_fyrtur
      - cover.ikea_fyrtur_2
      - cover.ikea_fyrtur_3

sensor:
  - platform: mqtt
    name: Battery Fyrtur
    state_topic: zigbee2mqtt/ikea_fyrtur
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"


  - platform: mqtt
    name: Battery Fyrtur 2
    state_topic: zigbee2mqtt/ikea_fyrtur_2
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

  - platform: mqtt
    name: Battery Fyrtur 3
    state_topic: zigbee2mqtt/ikea_fyrtur_3
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

homeassistant:
  customize:
    cover.ikea_fyrtur:
      friendly_name: Left Shade
      device_class: shade
    cover.ikea_fyrtur_2:
      friendly_name: Middle Shade
      device_class: shade 
    cover.ikea_fyrtur_3:
      friendly_name: Right Shade
      device_class: shade
