binary_sensor:
  - platform: "mqtt"
    name: Xiaomi Contact Sensor
    state_topic: "zigbee2mqtt/xiaomi_contact_sensor"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
    json_attributes_topic: "zigbee2mqtt/xiaomi_contact_sensor" 

  - platform: "mqtt"
    name: Xiaomi Contact Sensor 2
    state_topic: "zigbee2mqtt/xiaomi_contact_sensor_2"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
    json_attributes_topic: "zigbee2mqtt/xiaomi_contact_sensor_2"

  - platform: "mqtt"
    name: Xiaomi Contact Sensor 3
    state_topic: "zigbee2mqtt/xiaomi_contact_sensor_3"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
    json_attributes_topic: "zigbee2mqtt/xiaomi_contact_sensor_3"

homeassistant:
  customize:
    binary_sensor.xiaomi_contact_sensor:
      friendly_name: Front Door
    binary_sensor.xiaomi_contact_sensor_2:
      friendly_name: Bathroom Door
    binary_sensor.xiaomi_contact_sensor_3:
      friendly_name: Fridge Door
