binary_sensor:
  - platform: "mqtt"
    name: Contact Sensor 3
    state_topic: "zigbee2mqtt/aqara_contact_sensor_3"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
    json_attributes_topic: "zigbee2mqtt/aqara_contact_sensor_3"

automation:
  - id: fridge_door_open
    alias: Fridge Door Open
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_sensor_3
        to: 'on'
        for:
          seconds: 45
    action:
      - service: script.broadcast
        data:
          message: 'Fridge door did not close corectly'
      - wait_template: "{{ is_state('binary_sensor.contact_sensor_3', 'off') }}"
      - service: script.broadcast
        data:
          message: 'Fridge door was closed'

homeassistant:
  customize:
    binary_sensor.contact_sensor_3:
      friendly_name: Fridge
      icon: mdi:fridge-outline
