binary_sensor:
  - platform: "mqtt"
    name: Contact Sensor
    state_topic: "zigbee2mqtt/aqara_contact_sensor"
    #    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
    json_attributes_topic: "zigbee2mqtt/aqara_contact_sensor" 

automation:
  - id: turn_on_dnd_when_door_is_open
    alias: Turn on DND when door is open
    trigger:
      - platform: state
        entity_id: binary_sensor.door
    action:
      - service_template: "input_boolean.turn_{{trigger.to_state.state}}"
        entity_id: input_boolean.do_not_disturb

homeassistant:
  customize:
    binary_sensor.contact_sensor:
      friendly_name: Front Door
