#xiaomi_aqara:
#  gateways:
#    - key: !secret xiaomi_aqara_key

binary_sensor:
  - platform: mqtt
    name: zigbee2mqtt_state
    state_topic: zigbee2mqtt/bridge/state 
    payload_on: online
    payload_off: offline

homeassistant:
  customize:
    light.gateway_light_7811dce1e53e:
      icon: mdi:circle-outline
      friendly_name: Xiaomi Light

    binary_sensor.zigbee2mqtt_state:
      icon: mdi:zigbee
      friendly_name: Zigbee

