light:
  - platform: mqtt
    name: Aqara White Bulb
    state_topic: "zigbee2mqtt/aqara_white_bulb"
    brightness: true
    color_temp: true
    schema: "json"
    command_topic: "zigbee2mqtt/aqara_white_bulb/set"

yeelight:
  devices:
    10.10.10.193:
      name: LED Strip
      model: strip1

homeassistant:
  customize:
    light.aqara_white_bulb:
    friendly_name: Kitchen Light

    light.led_strip:
      icon: mdi:led-strip-variant
      friendly_name: Desk Light
