
sensor:
  - platform: "mqtt"
    name: Xiaomi Vibration Sensor
    state_topic: "zigbee2mqtt/xiaomi_vibration_sensor"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
    json_attributes_topic: "zigbee2mqtt/xiaomi_vibration_sensor"

