input_boolean:
  bathroom_in_use:
    name: Bathroom in use

binary_sensor:
  - platform: "template"
    sensors:
      bathroom_occupied:
        friendly_name: Bathroom
        value_template: "{{ is_state('input_boolean.bathroom_in_use', 'on') }}"
        device_class: occupancy

automation:
# IN USE AUTOMATION 

  # Motion when the door is closed
  # Bathroom is in use
  - id: bathroom_in_use
    alias: Bathroom in use
    trigger:
      - platform: state
        entity_id: binary_sensor.aqara_motion_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.contact_sensor_2
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bathroom_in_use

  # Door is opened
  # Bathroom is not in use
  - id: bathroom_not_in_use
    alias: Bathroom not in use
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_sensor_2
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bathroom_in_use
  
# LIGHT AUTOMATION

  # Turn on the light
  - id: bathroom_light_on
    alias: Bathroom Light On
    trigger:
      - platform: state
        entity_id: binary_sensor.aqara_motion_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.contact_sensor_2
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.tradfri_control_outlet_light

  # Turn off the light
  - id: bathroom_light_off
    alias: Bathroom Light Off
    trigger:
      - platform: state
        entity_id: binary_sensor.aqara_motion_sensor
        to: 'off'
        for:
          minutes: 3
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: 'off'
        for:
          seconds: 5
    condition:
      - condition: state
        entity_id: binary_sensor.bathroom_occupied
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.tradfri_control_outlet_light

homeassistant:
  customize:
    binary_sensor.bathroom_occupied:
      icon: mdi:run
