sensor:
  - platform: "mqtt"
    name: Tradfri Dimmer
    state_topic: "zigbee2mqtt/tradfri_dimmer"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "brightness"
    icon: "mdi:brightness-5"
    value_template: "{{ value_json.brightness }}"
    json_attributes_topic: "zigbee2mqtt/tradfri_dimmer"


automation:
  - id: light_dimmer
    alias: Light dimmer
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: group.room_lights
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.aqara_white_bulb
        data_template:
          brightness: "{{ trigger.to_state.state }}" 
  
  - id: light_dimmer_aqara_white_bulb
    alias: Light dimmer Aqara white bulb
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: light.aqara_white_bulb
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.aqara_white_bulb
        data_template:
          brightness: "{{ trigger.to_state.state }}"
  
  - id: light_dimmer_milight_rgbw_bulb
    alias: Light dimmer Milight RGBW bulb
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: light.milight_rgbw_bulb
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.milight_rgbw_bulb
        data_template:
          brightness: "{{ trigger.to_state.state }}"
  
  - id: light_dimmer_led_strip_1
    alias: Light dimmer LED strip 1
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: light.led_strip_1
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.led_strip_1
        data_template:
          brightness: "{{ trigger.to_state.state }}"
  
  - id: light_dimmer_led_strip_2
    alias: Light dimmer LED strip 2
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: light.led_strip_2     
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.led_strip_2     
        data_template:
          brightness: "{{ trigger.to_state.state }}"
  
  - id: light_dimmer_candela
    alias: Light dimmer Candela
    trigger:
      - platform: state
        entity_id: sensor.tradfri_dimmer
    condition:
      - condition: state
        entity_id: light.candela     
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.candela     
        data_template:
          brightness: "{{ trigger.to_state.state }}"
