automation:
  - id: heater_led_heat 
    alias: Heater LED 100
    trigger:
      - platform: state
        entity_id: climate.thermostat
        to: 'heat'
    action:
      - service: light.turn_on 
        entity_id: light.heater_led
        data:
          brightness_pct: 100
  
  - id: heater_led_idle
    alias: Heater LED 25
    trigger:
      - platform: state
        entity_id: climate.thermostat
        to: 'idle'
    action:
      - service: light.turn_on
        entity_id: light.heater_led
        data:
          brightness_pct: 25
  
  - id: heater_led_off
    alias: Heater LED off
    trigger:
      - platform: state
        entity_id: climate.thermostat
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.heater_led
  
  - id: heater_button_on 
    alias: Heater button on
    trigger:
      - platform: state
        entity_id: binary_sensor.heater_button
        from: 'off'
        to: 'on'
    action: 
      - service_template: "climate.turn_{{ 'on' if is_state('climate.thermostat', 'off') else 'off' }}"
        entity_id: climate.thermostat
  
