# When it's 00:00

- alias: Dim at midnight
  trigger:
    - platform: time
      at: '00:00:00'

  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'

  action:
    - service: scene.turn_on
      data: 
        entity_id: scene.midnight