# When it's 01:00

- alias: Go to bed
  trigger:
    - platform: time
      at: '01:00:00'

  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'

  action:
    - service: scene.turn_off
      entity_id: group.all_lights