# On TV off

- alias: Television off
  trigger:
    - platform: state
      entity_id: switch.television
      state: 'off'

  action:
    - service: group.set_visibility
      entity_id: group.media_players
      data:
        visible: False
