# On TV on

- alias: Television on
  trigger:
    - platform: state
      entity_id: switch.television
      state: 'on'

  action:
    - service: group.set_visibility
      entity_id: group.media_players
      data:
        visible: True

