homekit:
  name: Hassio
  auto_start: false
  filter:
    include_entities:
      - media_player.television
      - light.ikea_rgbw_bulb
      - light.ikea_rgbw_bulb_2
      - light.xiaomi_ww_bulb
      - light.led_strip
      - light.string_lights
      - switch.ikea_control_outlet  # Air purifier
      - switch.entone
      - switch.receiver
      - cover.ikea_fyrtur
      - cover.ikea_fyrtur_2
      - cover.ikea_fyrtur_3
      - binary_sensor.xiaomi_contact_sensor  # Door
      - binary_sensor.xiaomi_contact_sensor_2  # Bathroom door
      - binary_sensor.xiaomi_contact_sensor_3  # Fridge door
      - binary_sensor.kitchen_occupancy
      - binary_sensor.bathroom_occupancy
      - binary_sensor.living_room_occupancy
      - sensor.xiaomi_temperature
      - sensor.xiaomi_temperature_2
      - sensor.xiaomi_humidity
      - sensor.xiaomi_humidity_2

  entity_config:
    switch.socket:
      type: outlet
    switch.ikea_control_outlet:
      type: outlet
    switch.ikea_control_outlet_2:
      type: outlet
    switch.entone:
      type: outlet
    switch.receiver:
      type: outlet
    media_player.television: 
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute 
    cover.fyrtur:
      linked_battery_sensor: sensor.battery_fyrtur
    cover.fyrtur_2:
      linked_battery_sensor: sensor.battery_fyrtur_2
    cover.fyrtur_3:
      linked_battery_sensor: sensor.battery_fyrtur_3


binary_sensor:
  - platform: template
    sensors:
      homekit_ready:
        friendly_name: HomeKit Ready
        value_template: >-
          {% if is_state("light.led_strip", "unavailable") or
                is_state("switch.entone", "unavailable") or
                not states("binary_sensor.xiaomi_contact_sensor") in ["on", "off"] or
                not states("binary_sensor.xiaomi_motion_sensor") in ["on", "off"] or
                not states("cover.ikea_fyrtur") in ["open", "closed"] or
                not states("light.ikea_rgbw_bulb") in ["on", "off"] or
                not states("light.xiaomi_ww_bulb") in ["on", "off"]
          %}
            False
          {% else %}
            True
          {% endif %}

script:
  start_homekit:
    sequence:
      - wait_template: "{{ is_state('binary_sensor.homekit_ready', 'on') }}"
      - service: homekit.start

automation:
  - alias: Start HomeKit
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.start_homekit 
