
sensor:
  - platform: "mqtt"
    name: Xiaomi Vibration Sensor
    state_topic: "zigbee2mqtt/xiaomi_vibration_sensor"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
    json_attributes_topic: "zigbee2mqtt/xiaomi_vibration_sensor"

automation:
  - id: vibration_sensor
    alias: Vibration Sensor
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_vibration_sensor
    condition:
      - condition: template
        value_template: "{{  trigger.to_state.state != '' and trigger.to_state.state != 'unknown' }}"
    action:
      - service: notify.mobile_app_iphone_8
        data_template:
          message: "Bed is '{{ trigger.to_state.state }}'"
