sensor:
  - platform: "mqtt"
    name: Xiaomi Wall Switch
    state_topic: "zigbee2mqtt/xiaomi_wall_switch"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
    json_attributes_topic: "zigbee2mqtt/xiaomi_wall_switch"
    force_update: true

automation:
  - id: xiaomi_wall_switch_left
    alias: Xiaomi Wall Switch Left
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/xiaomi_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        entity_id: light.xiaomi_rgbw_bulb_2
  
  - id: xiaomi_wall_switch_right
    alias: Xiaomi Wall Switch Right
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/xiaomi_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        entity_id: light.ikea_rgbw_bulb
  
  - id: xiaomi_wall_switch_both
    alias: Xiaomi Wall Switch Both
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/xiaomi_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'both' }}"
    action:
      - service: scene.turn_on
        entity_id: scene.leave_home