apple_tv:
  - host: 10.10.10.4
    login_id: !secret apple_tv_id

automation:
  - id: apple_tv_started_playing
    alias: Apple TV started playing
    trigger:
      - platform: state
        entity_id: media_player.apple_tv
        to: 'playing'
    action:
      - wait_template: "{{ is_state('binary_sensor.television', 'on') }}"
        timeout: '00:01:00'
        continue_on_timeout: 'false'
      - service_template: input_boolean.turn_on
        entity_id: input_boolean.do_not_disturb
      - service: media_player.media_pause
        entity_id: media_player.sonos

        #- id: apple_tv_stopped_playing
        #    alias: Apple TV stopped playing
        #    trigger:
        #      - platform: state
        #        entity_id: media_player.apple_tv
        #        from: 'playing'
        #    action:
        #      - service_template: input_boolean.turn_off
        #        entity_id: input_boolean.do_not_disturb

  - id: pause_apple_tv
    alias: Pause Apple TV
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.apple_tv
        state: 'playing'
    action:
      - service: media_player.media_pause
        entity_id: media_player.apple_tv
      - wait_template: "{{ is_state(trigger.entity_id, 'off') }}"
      - service: media_player.media_play
        entity_id: media_player.apple_tv

  - id: television_turned_off_stop_apple_tv
    alias: Television turned off stop Apple TV
    trigger:
      - platform: state
        entity_id: switch.television
        to: 'off'
    action:
      - service: media_player.media_stop
        entity_id: media_player.apple_tv

script:
  apple_tv_airplay:
    alias: Apple TV AirPort Audio Output
    sequence:
      - alias: Wake up Apple TV
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - up
  
      - wait_template: "{{ not is_state('media_player.apple_tv', 'playing') and not is_state('media_player.apple_tv', 'off') }}"
  
      - alias: Open Settings
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - top_menu
            - down
            - down
            - down
            - right
            - right
            - right
            - up
            - up
            - select
            
      - alias: Go to Audio
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - down
            - down
            - down
            - down
            - down
            - down
  
      - delay:
          seconds: 1
  
      - alias: Select Audio
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - select
  
      - alias: Switch to AirPlay
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - down
            - down
            - down
            - down
            - down
            - down
  
      - delay:
          seconds: 1
  
      - alias: Confirm
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - select
            - top_menu
            - right
            - right
            - right
  
