automation:
  - id: apple_tv_airplay_audio
    alias: Switch to AirPlay audio output on startup
    trigger:
      - platform: state
        entity_id: media_player.apple_tv
        from: 'off'
    action:
      - delay:
          seconds: 10
      - service: script.turn_on
        entity_id: script.apple_tv_airplay

script:
  apple_tv_airplay:
    alias: Apple TV AirPort Audio Output
    sequence:
      - alias: Wake up Apple TV
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - up
  
      - wait_template: "{{ not is_state('media_player.apple_tv', 'playing') and not is_state('media_player.apple_tv', 'off') }}"
  
      - alias: Open Settings
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - top_menu
            - down
            - down
            - down
            - right
            - right
            - right
            - up
            - up
            - select
            
      - alias: Go to Audio
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - down
            - down
            - down
            - down
            - down
            - down
  
      - delay:
          seconds: 1
  
      - alias: Select Audio
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - select
  
      - alias: Switch to AirPlay
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - down
            - down
            - down
            - down
            - down
            - down
  
      - delay:
          seconds: 1
  
      - alias: Confirm
        service: remote.send_command
        data:
          entity_id: remote.apple_tv
          command:
            - select
            - top_menu
            - right
            - right
            - right
  
