sensor:
  - platform: template
    sensors:
      battery_door:
        value_template: "{{ state_attr('binary_sensor.door', 'battery') }}"
      battery_window:
        value_template: "{{ state_attr('binary_sensor.window', 'battery') }}"
      battery_aqara_motion_sensor:
        value_template: "{{ state_attr('binary_sensor.aqara_motion_sensor', 'battery') }}"
      battery_aqara_humidity:
        value_template: "{{ state_attr('sensor.aqara_humidity', 'battery') }}"


automation:
  # Low battery
  - id: notification_low_battery
    alias: Notification Low Battery
    trigger:
      - platform: numeric_state
        entity_id: sensor.aqara_button     
        value_template: '{{ state.attributes.battery }}'
        below: 11
      - platform: numeric_state
        entity_id: sensor.aqara_illuminance
        value_template: '{{ state.attributes.battery }}'
        below: 11
      - platform: numeric_state
        entity_id: sensor.aqara_temperature    
        value_template: '{{ state.attributes.battery }}'
        below: 11
      - platform: numeric_state
        entity_id: sensor.aqara_temperature_2
        value_template: '{{ state.attributes.battery }}'
        below: 11
      - platform: numeric_state
        entity_id: sensor.mijia_switch       
        value_template: '{{ state.attributes.battery }}'
        below: 11
    action:
      - service: persistent_notification.create
        data_template:
          message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} {{ trigger.entity_id.split('.')[0] }} is at {{ state_attr(trigger.entity_id, 'battery') | int }}% battery."
          title: "Battery warning"

  - id: notification_low_battery_mi_flora
    alias: Notification Low Battery Mi Flora
    trigger:
      - platform: numeric_state
        entity_id: sensor.mi_flora_battery
        below: 11
    action:
      - service: persistent_notification.create
        data_template:
          message: "Plant sensor is at {{ states('sensor.mi_flora_battery') | int }}% battery."
          title: "Battery warning"
