sensor:
  - platform: "mqtt"
    name: Mijia Button
    state_topic: "zigbee2mqtt/mijia_button"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
    json_attributes_topic: "zigbee2mqtt/mijia_button"
    force_update: true


automation:
  # SINGLE PRESS
  - id: single_press_morning
    alias: Single Press Morning 
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_button
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'single' }}"
      - condition: state
        entity_id: input_select.home_status
        state: 'Home'
      - condition: time
        after: '06:00:00'
        before: '12:00:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.alarm_clock
  
  - id: single_press_dark_mode
    alias: Single Press Dark Mode
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_button
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'single' }}"
      - condition: state
        entity_id: input_select.home_status
        state: 'Home'
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.dark_mode
  
  - id: single_press_night 
    alias: Single Press Night
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_button
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'single' }}"
      - condition: state
        entity_id: input_select.home_status
        state: 'Night'
    action:
      - service: light.toggle
        entity_id: light.night_light
  
  # DOUBLE PRESS
  - id: button_toggle_air_purifier
    alias: toggle air purifier
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_button
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'double' }}"
    action:
      - service: switch.toggle
        entity_id: switch.air_purifier
  
  # TRIPLE PRESS
  
  # QUADRUPLE PRESS
  
  # MANY PRESS
  
  # LONG PRESS
  - id: long_press_home_status
    alias: Long Press in the evening
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_button
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'long' }}"
    action:
      - service: input_select.select_option
        entity_id: input_select.home_status
        data_template:
          option: >
            {% if states('input_select.home_status') == 'Home' %}
              Night
            {% else %}
              Home
            {% endif %}
  
  # LONG_RELEASE PRESS
  # TODO tts home status
