homekit:
  filter:
    include_entities:
      - binary_sensor.contact_sensor
      - binary_sensor.contact_sensor_2
      - binary_sensor.contact_sensor_3
      - binary_sensor.aqara_motion_sensor
      - binary_sensor.mijia_motion_sensor
      - binary_sensor.mijia_motion_sensor_2
      - binary_sensor.bathroom_occupied
      - cover.fyrtur
      - cover.fyrtur_2
      - cover.fyrtur_3
      - light.aqara_white_bulb
      - light.tradfri_rgbw_bulb
      - light.tradfri_control_outlet_light
      - light.gateway_light_7811dce1e53e
        #      - light.led_strip
      - media_player.television
      - sensor.aqara_humidity
      - sensor.aqara_humidity_2
      - sensor.aqara_temperature
      - sensor.aqara_temperature_2
      - switch.air_purifier
      - switch.entone
      - switch.tradfri_control_outlet
      - input_boolean.do_not_disturb
      - device_tracker.macbook_pro
      - person.roman_peters

  entity_config:
    binary_sensor.bathroom_occupied:
      name: Bathroom Occupied
    binary_sensor.contact_sensor:
      name: Living Room Door
      linked_battery_sensor: sensor.battery_contact_sensor
    binary_sensor.contact_sensor_2:
      linked_battery_sensor: sensor.battery_contact_sensor_2
    binary_sensor.contact_sensor_3:
      linked_battery_sensor: sensor.battery_contact_sensor_3
    binary_sensor.aqara_motion_sensor:
      name: Bathroom Motion Sensor
      linked_battery_sensor: sensor.battery_aqara_motion_sensor
    sensor.aqara_humidity:
      name: Living Room Humidity
      linked_battery_sensor: sensor.battery_aqara_humidity
    sensor.aqara_temperature:
      name: Living Room Temperature
      linked_battery_sensor: sensor.battery_aqara_humidity
    sensor.aqara_humidity_2:
      linked_battery_sensor: sensor.battery_aqara_humidity_2
    sensor.aqara_vibration:
      linked_battery_sensor: sensor.battery_aqara_vibration
    person.roman_peters:
      name: Roman

    switch.socket:
      type: outlet
    switch.tradfri_control_outlet:
      type: outlet
    media_player.living_room:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute


device_tracker:
  - platform: mqtt
    devices:
      homekit: 'homekit/home'

switch:
  - platform: mqtt
    name: Do Not Disturb
    command_topic: 'homekit/dnd'
    icon: mdi:moon-waning-crescent


input_boolean:
  autowake:
    name: AutoWake

alarm_control_panel:
  - platform: manual
    name: Home Status
#    disarmed:
#      trigger_time: 0
    armed_home:
      pending_time: 0
    armed_away:
      pending_time: 0
    armed_night:
      pending_time: 0

automation:
  - id: input_boolean_home_to_alarm_system
    alias: Input Boolean Home to Alarm System
    trigger:
      - platform: state
        entity_id: switch.home
    condition:
      - condition: template
        value_template: "{{ not is_state('input_select.home_status', 'Off') }}"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {%- if is_state('switch.home', 'on') -%}
              Home
            {%- else -%}
              Away
            {% endif %}


  - id: home_status_to_alarm_system
    alias: Home Status to Alarm System
    trigger:
      - platform: state
        entity_id: input_select.home_status
    action:
      - service_template: "alarm_control_panel.alarm_arm_{{ states('input_select.home_status') | lower }}"
        entity_id: alarm_control_panel.home_status

  - id: alarm_system_to_home_status
    alias: Alarm System to Home Status
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_status
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {% if states('alarm_control_panel.home_status') == 'disarmed' %}
              Off
            {% else %}
              {{ states('alarm_control_panel.home_status').split('_')[-1] | title }}
            {% endif %}

homeassistant:
  customize:
    switch.do_not_disturb:
      assumed_state: True
