homekit:
  filter:
    include_entities:
      - binary_sensor.door
      - binary_sensor.window
      - binary_sensor.motion_sensor_sensor
      - light.aqara_white_bulb
      - light.gateway_light_7811dce1e53e
      - media_player.television
      - sensor.aqara_humidity
      - switch.air_purifier
      - switch.home
      - switch.entone
      - switch.tradfri_control_outlet

  entity_config:
    binary_sensor.door:
      linked_battery_sensor: sensor.battery_door
    binary_sensor.window:
      linked_battery_sensor: sensor.battery_window
    binary_sensor.aqara_motion_sensor:
      linked_battery_sensor: sensor.battery_aqara_motion_sensor
    sensor.aqara_humidity:
      linked_battery_sensor: sensor.battery_aqara_humidity

    switch.socket:
      type: outlet
    switch.tradfri_control_outlet:
      type: outlet
    media_player.living_room:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute


device_tracker:
  - platform: mqtt
    devices:
      homekit: 'homekit/home'

switch:
  - platform: mqtt
    name: Home
    command_topic: 'homekit/home'
    payload_on: 'home'
    payload_off: 'not_home'

input_boolean:
  autowake:
    name: AutoWake

alarm_control_panel:
  - platform: manual
    name: Home Status
#    disarmed:
#      trigger_time: 0
    armed_home:
      pending_time: 0
    armed_away:
      pending_time: 0
    armed_night:
      pending_time: 0

automation:
  - id: input_boolean_home_to_alarm_system
    alias: Input Boolean Home to Alarm System
    trigger:
      - platform: state
        entity_id: switch.home
    condition:
      - condition: template
        value_template: "{{ not is_state('input_select.home_status', 'Off') }}"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {%- if is_state('switch.home', 'on') -%}
              Home
            {%- else -%}
              Away
            {% endif %}


  - id: home_status_to_alarm_system
    alias: Home Status to Alarm System
    trigger:
      - platform: state
        entity_id: input_select.home_status
    action:
      - service_template: "alarm_control_panel.alarm_arm_{{ states('input_select.home_status') | lower }}"
        entity_id: alarm_control_panel.home_status

  - id: alarm_system_to_home_status
    alias: Alarm System to Home Status
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_status
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.home_status
          option: >
            {% if states('alarm_control_panel.home_status') == 'disarmed' %}
              Off
            {% else %}
              {{ states('alarm_control_panel.home_status').split('_')[-1] | title }}
            {% endif %}

