switch:
  - platform: rest
    resource: http://10.10.10.20:8126/container/minecraft-server
    name: Minecraft Server
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

binary_sensor:
  - platform: "template"
    sensors:
      minecraft_server:
        delay_on: 
          minutes: 5
        value_template: "{{ is_state('switch.minecraft_server', 'on') }}"

automation:
  - id: notification_minecraft_server
    alias: Notification Minecraft Server
    trigger: 
      - platform: state
        entity_id: binary_sensor.minecraft_server
    action:
      service: script.broadcast
      data_template:
        title: "Minecraft Server"
        message: "Server turned {{ trigger.to_state.state }}"

homeassistant:
  customize:
    binary_sensor.minecraft_server:
      icon: mdi:minecraft
      friendly_name: Minecraft Server
