input_text:
  siri:
    name: Siri
    initial: ""

automation:
  - alias: Ask Siri
    trigger:
      platform: state
      entity_id: input_text.siri
      from: ""
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.intel_nuc
          message: "Hey Siri, {{ states('input_text.siri') }}"
      - service: input_text.set_value
        data_template:
          entity_id: input_text.siri
          value: ""

homeassistant:
  customize:
    input_text.siri:
      icon: mdi:apple-finder
