binary_sensor:
  - platform: tod
    name: Morning
    after: '06:00'
    before: '12:00'

  - platform: tod
    name: Afternoon
    after: '12:00'
    before: '18:00'

  - platform: tod
    name: Evening
    after: '18:00'
    before: '00:00'

  - platform: tod
    name: Night
    after: '00:00'
    before: '06:00'
  
  - platform: tod
    name: Bed Time
    after: '00:00'
    before: '03:00'

  - platform: tod
    name: Dark
    after: sunset
    after_offset: '-00:15'
    before: sunrise


