automation:
  - id: turn_turtle_mode_on
    alias: Turn Turtle Mode On
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'on'
      - platform: state
        entity_id: binary_sensor.night_mode
        to: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.transmission_turtle_mode

  - id: turn_turtle_mode_off
    alias: Turn Turtle Mode Off
    trigger:
      - platform: state
        entity_id: binary_sensor.home
        to: 'off'
      - platform: state
        entity_id: binary_sensor.night_mode
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.transmission_turtle_mode

homeassistant:
  customize:
    switch.transmission_turtle_mode:
      friendly_name: Throttle Downloads
      icon: mdi:turtle
