sensor:
  - platform: "mqtt"
    name: Aqara Wall Switch
    state_topic: "zigbee2mqtt/aqara_wall_switch"
    #    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
    json_attributes_topic: "zigbee2mqtt/aqara_wall_switch"
    force_update: true

automation:
  - id: wall_switch_left
    alias: wall switch left
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'left' }}"
    action:
      - service: light.toggle
        entity_id: light.aqara_white_bulb
  
  - id: wall_switch_right
    alias: wall switch right
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'right' }}"
    action:
      - service: light.toggle
        entity_id: light.tradfri_rgbw_bulb
  
  - id: wall_switch_both
    alias: wall switch both
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/aqara_wall_switch
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.click == 'both' }}"
    action:
      - service: light.turn_off
        entity_id: group.all_lights
