xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_aqara_key

binary_sensor:
  - platform: template
    sensors:
      motion_sensor_sensor: 
        value_template: "{{ is_state('binary_sensor.aqara_motion_sensor', 'on') }}"
        friendly_name: Motion Sensor
        delay_off:
          minutes: 5


homeassistant:
  customize:
    light.gateway_light_7811dce1e53e:
      icon: mdi:circle
      friendly_name: Xiaomi Light
